server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
    level:
      com.ecommerce.ordermanagement: DEBUG
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    data:
      redis:
        host: localhost
        port: 6379
    cache:
      time-to-live: 600000
      cache-null-values: false

    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: order-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer